export { BaseDictionaryAdapter } from './base'
export { OnlineDictionaryAdapter } from './online'
export { LocalDictionaryAdapter } from './local'
export { CambridgeDictionaryAdapter } from './cambridge'
export { DictionaryAdapterManager, dictionaryManager } from './manager'
